[project]
name = "iota"
version = "0.1.0"
authors = ["Greg Chapple <gregchapple1@gmail.com>"]

[dependencies]
docopt = "0.6.16"

[dependencies.rustbox]
git = "https://github.com/gchp/rustbox"

[dependencies.gapbuffer]
git = "https://github.com/dlaronson/gapbuffer"

[lib]
name = "iota"
path = "src/iota/lib.rs"

[[bin]]
name = "iota"
doc = false
